sekolah/adm_sekolah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('utama.urls')),
    path('siswa/', include('siswa.urls')),
    path('tagihan/', include('keuangan.urls')),
    path('staff/', include('karyawan.urls'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sekolah/siswa/urls.py
from django.urls import path

from . import views

app_name = 'siswa'

urlpatterns = [
    path('baru/', views.SiswaAdd.as_view(), name='baru'),
    path('update/<int:pk>/', views.SiswaEdit.as_view(), name='update'),
    path('detail/<int:pk>/', views.SiswaDetail.as_view(), name='detail'),
    path('', views.SiswaList.as_view(), name='murid'),
]

sekolah/utama/urls.py
from django.urls import path

from . import views

app_name = 'utama'
urlpatterns = [
    path('dev/', views.developer, name='dev'),
    path('setting/tahun-pelajaran/', views.TahunPelajaranView.as_view(), name='ta-list'),
    path('setting/tahun-pelajaran/add/', views.TahunPelajaranAdd.as_view(), name='ta-add'),
    path('setting/tahun-pelajaran/<int:pk>/edit/', views.TahunPelajaranEdit.as_view(), name='ta-edit'),
    path('setting/tahun-pelajaran/<int:pk>/del/', views.TahunPelajaranDel.as_view(), name='ta-del'),
    path('setting/semester/', views.SemesterView.as_view(), name='smt-list'),
    path('setting/semester/add/', views.SemesterAdd.as_view(), name='smt-add'),
    path('setting/semester/<int:pk>/edit/', views.SemesterEdit.as_view(), name='smt-edit'),
    path('setting/semester/<int:pk>/del/', views.SemesterDel.as_view(), name='smt-del'),
    path('setting/kelas/', views.KelasView.as_view(), name='kls-list'),
    path('setting/kelas/add/', views.KelasAdd.as_view(), name='kls-add'),
    path('setting/kelas/<int:pk>/edit/', views.KelasEdit.as_view(), name='kls-edit'),
    path('setting/kelas/<int:pk>/del/', views.KelasDel.as_view(), name='kls-del'),
    path('setting/mapel/', views.MapelView.as_view(), name='mpl-list'),
    path('setting/mapel/add/', views.MapelAdd.as_view(), name='mpl-add'),
    path('setting/mapel/<int:pk>/edit/', views.MapelEdit.as_view(), name='mpl-edit'),
    path('setting/mapel/<int:pk>/del/', views.MapelDel.as_view(), name='mpl-del'),
    path('setting/biaya/', views.BiayaMasuk.as_view(), name='biaya'),
    path('setting/biaya/pendaftaran/', views.BiayaAdd.as_view(), name='bi-add'),
    path('setting/biaya/<int:pk>/edit/', views.BiayaEdit.as_view(), name='bi-edit'),
    path('', views.index_utama, name='index'),
]

sekolah/utama/models.py
from django.db import models

# Create your models here.
class TahunPelajaran(models.Model):
    name = models.CharField(max_length=200, unique=True)
    sekarang = models.BooleanField(default=False, null=True)

    class Meta:
        ordering = ['-name']
    
    def __str__(self):
        return str(self.name)

class Semester(models.Model):
    SEMETER = {
        ('genap', 'Genap'),
        ('ganjil', 'Ganjil'),
    }
    name = models.CharField(choices=SEMETER, max_length=10)
    sekarang = models.BooleanField(default=False, null=True)

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name

class Kelas(models.Model):
    name = models.CharField(max_length=10, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Mapel(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name

class BiayaPendaftaran(models.Model):
    tahun_pelajaran = models.OneToOneField(TahunPelajaran, on_delete=models.CASCADE)
    uang_masuk = models.CharField(max_length=200)

    class Meta:
        ordering = ['tahun_pelajaran']
    
    def __str__(self):
        return self.tahun_pelajaran

sekolah/utama/forms.py
from django.forms import ModelForm
from . import models

class TahunPelajaranForm(ModelForm):
    prefix = 'tahun_pelajaran'
    class Meta:
        model = models.TahunPelajaran
        fields = '__all__'

class SemesterForm(ModelForm):
    prefix = 'semester'
    class Meta:
        model = models.Semester
        fields = '__all__'

class KelasForm(ModelForm):
    prefix = 'kelas'
    class Meta:
        model = models.Kelas
        fields = '__all__'

class MapelForm(ModelForm):
    prefix = 'mata_pelajaran'
    class Meta:
        model = models.Mapel
        fields = '__all__'

class BiayaPendaftaranForm(ModelForm):
    prefix = 'biaya_pendaftaran'
    class Meta:
        model = models.BiayaPendaftaran
        fields = '__all__'

sekolah/utama/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from . import forms, models

# Create your views here.
def index_utama(request):
    return render(request, 'index.html')

@login_required
def developer(request):
    return render(request, 'developer.html')

# Tahun Pelajaran
class TahunPelajaranView(LoginRequiredMixin, ListView):
    queryset = models.TahunPelajaran.objects.all()

class TahunPelajaranAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = forms.TahunPelajaranForm
    template_name = 'utama/form_utama.html'
    success_message = 'Tahun pelajaran baru berhasil ditambah'
    success_url = reverse_lazy('utama:ta-list')
    extra_context = {
        'title': 'Tahun Pelajaran Baru'
    }

class TahunPelajaranEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    queryset = models.TahunPelajaran.objects.all()
    form_class = forms.TahunPelajaranForm
    template_name = 'utama/form_utama.html'
    success_message = 'Tahun pelajaran baru sudah diperbarui'
    success_url = reverse_lazy('utama:ta-list')
    extra_context = {
        'title': 'Update tahun pelajaran'
    }

class TahunPelajaranDel(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'utama/confirm_delete.html'
    success_message = 'Tahun pelajaran berhasil dihapus'
    success_url = reverse_lazy('utama:ta-list')
    extra_context = {
        'title': 'Hapus tahun pelajaran'
    }

    def get_queryset(self):
        self.queryset = models.TahunPelajaran.objects.filter(id=self.kwargs['pk'])
        return super().get_queryset()
    
    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.sekarang == True:
            messages.warning(request, 'Tidak bisa menghapus tahun pelajaran sekarang!!')
            return redirect('utama:ta-list')
        messages.success(self.request, self.success_message.format(obj.name))
        return super(TahunPelajaranDel, self).delete(request, *args, **kwargs)

# Semester
class SemesterView(LoginRequiredMixin, ListView):
    queryset = models.Semester.objects.all()

class SemesterAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = forms.SemesterForm
    template_name = 'utama/form_utama.html'
    success_message = 'Semester baru berhasil ditambah'
    success_url = reverse_lazy('utama:smt-list')
    extra_context = {
        'title': 'Semester Baru'
    }

class SemesterEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    queryset = models.Semester.objects.all()
    form_class = forms.SemesterForm
    template_name = 'utama/form_utama.html'
    success_message = 'Semester baru sudah diperbarui'
    success_url = reverse_lazy('utama:smt-list')
    extra_context = {
        'title': 'Update semester'
    }

class SemesterDel(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'utama/confirm_delete.html'
    success_message = 'Semester berhasil dihapus'
    success_url = reverse_lazy('utama:smt-list')
    extra_context = {
        'title': 'Hapus semester'
    }

    def get_queryset(self):
        self.queryset = models.Semester.objects.filter(id=self.kwargs['pk'])
        return super().get_queryset()
    
    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.sekarang == True:
            messages.warning(request, 'Tidak bisa menghapus semester sekarang!!')
            return redirect('utama:smt-list')
        messages.success(self.request, self.success_message.format(obj.name))
        return super(SemesterDel, self).delete(request, *args, **kwargs)

class KelasView(LoginRequiredMixin, ListView):
    queryset = models.Kelas.objects.all()

class KelasAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = forms.KelasForm
    template_name = 'utama/form_utama.html'
    success_message = 'Kelas baru berhasil ditambah'
    success_url = reverse_lazy('utama:kls-list')
    extra_context = {
        'title': 'Kelas Baru'
    }

class KelasEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    queryset = models.Kelas.objects.all()
    form_class = forms.KelasForm
    template_name = 'utama/form_utama.html'
    success_message = 'Kelas baru sudah diperbarui'
    success_url = reverse_lazy('utama:kls-list')
    extra_context = {
        'title': 'Update kelas'
    }

class KelasDel(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'utama/confirm_delete.html'
    success_message = 'Kelas berhasil dihapus'
    success_url = reverse_lazy('utama:kls-list')
    extra_context = {
        'title': 'Hapus kelas'
    }

    def get_queryset(self):
        self.queryset = models.Kelas.objects.filter(id=self.kwargs['pk'])
        return super().get_queryset()

class MapelView(LoginRequiredMixin, ListView):
    queryset = models.Mapel.objects.all()

class MapelAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = forms.MapelForm
    template_name = 'utama/form_utama.html'
    success_message = 'Mata Pelajaran baru ditambah'
    success_url = reverse_lazy('utama:mpl-list')
    extra_context = {
        'title': 'Mata Pelajaran'
    }

class MapelEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    queryset = models.Mapel.objects.all()
    form_class = forms.MapelForm
    template_name = 'utama/form_utama.html'
    success_message = 'Mata Pelajaran Update'
    success_url = reverse_lazy('utama:mpl-list')
    extra_context = {
        'title': 'Update Mata Pelajaran'
    }

class MapelDel(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'utama/confirm_delete.html'
    success_message = 'Mata Pelajaran berhasil dihapus'
    success_url = reverse_lazy('utama:mpl-list')
    extra_context = {
        'title': 'Hapus Mata Pelajaran'
    }

    def get_queryset(self):
        self.queryset = models.Mapel.objects.filter(id=self.kwargs['pk'])
        return super().get_queryset()

class BiayaMasuk(LoginRequiredMixin, ListView):
    queryset = models.BiayaPendaftaran.objects.all()

class BiayaAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = forms.BiayaPendaftaranForm
    template_name = 'utama/form_utama.html'
    success_message = 'Biaya Pendafaran baru ditambah'
    success_url = reverse_lazy('utama:biaya')
    extra_context = {
        'title': 'Biaya Pendaftaran'
    }

class BiayaEdit(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    queryset = models.BiayaPendaftaran.objects.all()
    form_class = forms.BiayaPendaftaranForm
    template_name = 'utama/form_utama.html'
    success_message = 'Biaya Pendaftaran Update'
    success_url = reverse_lazy('utama:biaya')
    extra_context = {
        'title': 'Update Biaya Pendaftaran'
    }

sekolah/templates/utama/biayapendaftaran_list.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Setting Biaya{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Setting</li>
<li><i class="fa fa-laptop"></i>Biaya Pendaftaran</li>
{% endblock breadcrumb %}

{% block heading %}
Biaya Pendaftaran {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<table class="table table-striped table-advance table-hover">
    <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr>
            <td>{{ object.tahun_pelajaran }}</td>
            <td>{{ object.uang_masuk }}</td>
            <td>
                <a href="{% url 'utama:bi-add' %}" class="btn btn-primary"><i class="icon_plus_alt2"></i></a>
                <a href="{% url 'utama:bi-edit' object.id %}" class="btn btn-success"><i class="fa fa-edit"></i></a> 
                <a href="#" class="btn btn-danger"><i class="icon_close_alt2"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td><h2>belum dibuat</h2></td>
            <td><a href="{% url 'utama:bi-add' %}">Buat baru</a></td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock content %}

sekolah/templates/utama/confirm_delete.html
{% extends 'html.html' %}
{% load widget_tweaks %}

{% block page_title %}{% block title %}{% block heading %}{{ title }}{% endblock %}{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="icon_document_alt"></i>Forms</li>
<li><i class="fa fa-file-text-o"></i>{{ title }}</li>
{% endblock breadcrumb %}

{% block content %}
<p>Apakah Anda yakin akan {{ title|lower }} <strong>{{ object }}</strong> dan seluruh content yang berhubungan dengannya?</strong></p>
<div class="alert alert-block alert-danger fade in">
    <button data-dismiss="alert" class="close close-sm" type="button">
        <i class="icon-remove"></i>
    </button>
    <strong>Peringatan !</strong> Aksi ini tidak dapat dibatalkan
</div>
<form method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Hapus permanen <i class="fa fa-trash-alt"></i></button>
</form>
{% endblock content %}

sekolah/templates/utama/form_utama.html
{% extends 'html.html' %}
{% load widget_tweaks %}

{% block page_title %}{% block title %}{% block heading %}{{ title }}{% endblock %}{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="icon_document_alt"></i>Forms</li>
<li><i class="fa fa-file-text-o"></i>{{ title }}</li>
{% endblock breadcrumb %}

{% block content %}
<form method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    {% for f in form %}
    <div class="form-group">
        {{ f | add_label_class:"col-sm-2 control-label" }}
        <div class="col-sm-10">
            {{ f | add_class:"form-control" | safe }}
            {{ f.help_text }}
        </div>
        {% if f.errors %}
        <div class="form-group"><i class="far fa-times-circle"></i>{{ f.errors }}</div>
        {% endif %}
    </div><br>
    {% endfor %}
    {% if object %}
    <input type="submit" class="btn btn-primary" value="Update data">
    {% else %}
    <input type="submit" class="btn btn-primary" value="Save">
    {% endif %}
</form>
{% endblock content %}

sekolah/templates/utama/kelas_list.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Setting Kelas{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Setting</li>
<li><i class="fa fa-laptop"></i>Kelas</li>
{% endblock breadcrumb %}

{% block heading %}
Kelas {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<table class="table table-striped table-advance table-hover">
    <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr>
            <td>{{ object }}</td>
            <td>
                <a href="{% url 'utama:kls-add' %}" class="btn btn-primary"><i class="icon_plus_alt2"></i></a>
                <a href="{% url 'utama:kls-edit' object.id %}" class="btn btn-success"><i class="fa fa-edit"></i></a> 
                <a href="{% url 'utama:kls-del' object.id %}" class="btn btn-danger"><i class="icon_close_alt2"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td><h2>Kelas belum dibuat</h2></td>
            <td><a href="{% url 'utama:kls-add' %}">Buat baru</a></td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock content %}

sekolah/templates/utama/mapel_list.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Setting Mata Pelajaran{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Setting</li>
<li><i class="fa fa-laptop"></i>Mata Pelajaran</li>
{% endblock breadcrumb %}

{% block heading %}
Mata Pelajaran {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<table class="table table-striped table-advance table-hover">
    <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr>
            <td>{{ object }}</td>
            <td>
                <a href="{% url 'utama:mpl-add' %}" class="btn btn-primary"><i class="icon_plus_alt2"></i></a>
                <a href="{% url 'utama:mpl-edit' object.id %}" class="btn btn-success"><i class="fa fa-edit"></i></a> 
                <a href="{% url 'utama:mpl-del' object.id %}" class="btn btn-danger"><i class="icon_close_alt2"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td><h2>Belum ada Mata Pelajaran</h2></td>
            <td><a href="{% url 'utama:mpl-add' %}">Buat baru</a></td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock content %}

sekolah/templates/utama/semester_list.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Setting Semester{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Setting</li>
<li><i class="fa fa-laptop"></i>Semester</li>
{% endblock breadcrumb %}

{% block heading %}
Semester {% if messages %}{% for message in messages %}<span class="text-success">| {{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<table class="table table-striped table-advance table-hover">
    <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr>
            <td>{{ object }}</td>
            <td>
                {% if object.sekarang == True %}
                Tahun Pelajaran Saat ini <i class="fa fa-check"></i>
                {% endif %}
            </td>
            <td>
                <a href="{% url 'utama:smt-add' %}" class="btn btn-primary"><i class="icon_plus_alt2"></i></a>
                <a href="{% url 'utama:smt-edit' object.id %}" class="btn btn-success"><i class="fa fa-edit"></i></a> 
                <a href="{% url 'utama:smt-del' object.id %}" class="btn btn-danger"><i class="icon_close_alt2"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td><h2>Belum ada semester</h2></td>
            <td><a href="{% url 'utama:smt-add' %}">Buat baru</a></td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock content %}

sekolah/templates/utama/tahunpelajaran_list.html
{% extends 'html.html' %}

{% block page_title %}{% block title %}Setting Tahun Pelajaran{% endblock %}{% endblock %}

{% block breadcrumb %}
<li><i class="fa fa-laptop"></i>Setting</li>
<li><i class="fa fa-laptop"></i>Tahun Pelajaran</li>
{% endblock breadcrumb %}

{% block heading %}
Tahun Pelajaran Berjalan {% if messages %}{% for message in messages %}<span class="text-success">{{ message }}</span>{% endfor %}{% endif %}
{% endblock heading %}

{% block content %}
<table class="table table-striped table-advance table-hover">
    <tbody>
        {% if object_list %}
        {% for object in object_list %}
        <tr>
            <td>{{ object }}</td>
            <td>
                {% if object.sekarang == True %}
                Tahun Pelajaran Saat ini <i class="fa fa-check"></i>
                {% endif %}
            </td>
            <td>
                <a href="{% url 'utama:ta-add' %}" class="btn btn-primary"><i class="icon_plus_alt2"></i></a>
                <a href="{% url 'utama:ta-edit' object.id %}" class="btn btn-success"><i class="fa fa-edit"></i></a> 
                <a href="{% url 'utama:ta-del' object.id %}" class="btn btn-danger"><i class="icon_close_alt2"></i></a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td><h2>Tahun pelajaran belum dibuat</h2></td>
            <td><a href="{% url 'utama:ta-add' %}">Buat baru</a></td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock content %}