sekolah/adm_sekolah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('utama.urls')),
    path('siswa/', include('siswa.urls')),
    path('tagihan/', include('keuangan.urls')),
    path('staff/', include('karyawan.urls'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sekolah/karyawan/urls.py
from django.urls import path

from .views import StaffListView, StaffDetailView, StaffCreateView, StaffUpdateView, StaffDeleteView

app_name = 'staff'
urlpatterns = [
    path('list/', StaffListView.as_view(), name='list'),
    path('detail/<pk>/', StaffDetailView.as_view(), name='detail'),
    path('create/', StaffCreateView.as_view(), name='create'),
    path('update/<pk>/', StaffUpdateView.as_view(), name='update'),
    path('delete/<pk>/', StaffDeleteView.as_view(), name='delete'),
]

sekolah/siswa/urls.py
from django.urls import path

from . import views

app_name = 'siswa'

urlpatterns = [
    path('baru/', views.SiswaAdd.as_view(), name='baru'),
    path('update/<int:pk>/', views.SiswaEdit.as_view(), name='update'),
    path('detail/<int:pk>/', views.SiswaDetail.as_view(), name='detail'),
    path('', views.SiswaList.as_view(), name='murid'),
]

sekolah/karyawan/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Staff(models.Model):
    STATUS = {
        ('active', 'Active'),
        ('inactive', 'Inactive')
    }
    GENDER = {
        ('pria', 'Pria'),
        ('wanita', 'Wanita')
    }
    status_sekarang = models.CharField(max_length=10, choices=STATUS, default='active')
    nama = models.CharField(max_length=100)
    alias = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER, default='pria')
    tanggal_lahir = models.DateField()
    tanggal_masuk = models.DateField()
    nomor_hp = models.CharField(max_length=15, blank=True, null=True)
    alamat = models.TextField(blank=True, null=True)
    catatan = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.nama, self.status_sekarang)
    
    def get_absolute_url(self):
        return reverse('staff:detail', kwargs={'pk': self.pk})

sekolah/karyawan/views.py
from django.shortcuts import render
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.forms import widgets
from django.urls import reverse_lazy

from .models import Staff

class StaffListView(ListView):
    model = Staff

class StaffDetailView(DetailView):
    model = Staff

class StaffCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Staff
    fields = '__all__'
    success_message = 'Karyawan sudah ditambah'

    def get_form(self):
        form = super(StaffCreateView, self).get_form()
        form.fields['tanggal_lahir'].widget = widgets.DateInput(
            attrs={'type': 'date'}
        )
        form.fields['tanggal_masuk'].widget = widgets.DateInput(
            attrs={'type': 'date'}
        )
        form.fields['alamat'].widget = widgets.Textarea(
            attrs={'rows': '1'}
        )
        form.fields['catatan'].widget = widgets.Textarea(
            attrs={'rows': '1'}
        )
        return form

class StaffUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Staff
    fields = '__all__'
    success_message = 'Karyawan sudah diubah'

    def get_form(self):
        form = super(StaffUpdateView, self).get_form()
        form.fields['tanggal_lahir'].widget = widgets.DateInput(
            attrs={'type': 'date'}
        )
        form.fields['tanggal_masuk'].widget = widgets.DateInput(
            attrs={'type': 'date'}
        )
        form.fields['alamat'].widget = widgets.Textarea(
            attrs={'rows': '1'}
        )
        form.fields['catatan'].widget = widgets.Textarea(
            attrs={'rows': '1'}
        )
        return form

class StaffDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Staff
    success_url = reverse_lazy('staff:list')

sekolah/templates/karyawan/staff_confirm_delete.html
{% extends 'html.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}

    <div class="alert">
        <p>Apakah yakin akan menghapus data "{{ object }}"?</p>
        <p>Semua data yang berhubungan dengan karyawan ini akan dihapus.</p>
    </div>
    <input type="submit" class="btn btn-primary" value="Hapus">
</form>
{% endblock %}

sekolah/templates/karyawan/staff_detail.html
{% extends 'html.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
        <div>
            <h3>{{ object }}</h3>
            <h5>{{ object.gender }}</h5>
            <h5>{{ object.tanggal_masuk }}</h5>
        </div>
    </div>

    <div class="col-sm-8">
        <div>
            <div class="form-group border-bottom row">
                <label class="col">
                    Tanggal Lahir
                </label>
                <div class="col">
                    {{ object.tanggal_lahir }}
                </div>
            </div>

            <div class="form-group border-bottom row">
                <label class="col">
                    Nomor HP
                </label>
                <div class="col">
                    {{ object.nomor_hp }}
                </div>
            </div>

            <div class="form-group border-bottom row">
                <label class="col">
                    Alamat
                </label>
                <div class="col">
                    {{ object.alamat }}
                </div>
            </div>

            <div class="form-group border-bottom row">
                <label class="col">
                    Catatan
                </label>
                <div class="col">
                    {{ object.catatan }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sekolah/templates/karyawan/staff_form.html
{% extends 'html.html' %}
{% load widget_tweaks %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">
        {{ field.label }}
        {% for error in field.errors %}
        <small id="{{ field.auto_id }}" class="text-danger">{{ error }}</small>
        {% endfor %}
    </label>

    <div class="col-sm-9">
        {{ field | add_class:"form-control" }}
        {% if field.help_text %}
        <small>{{ field.help_text | safe }}</small>
        {% endif %}
    </div>
    {% endfor %}

    {% if object %}
    <input type="submit" class="btn btn-primary" value="Update data">
    {% else %}
    <input type="submit" class="btn btn-primary" value="Simpan">
    {% endif %}
</form>
{% endblock %}

sekolah/templates/karyawan/staff_list.html
{% extends 'html.html' %}

{% block heading %}
<a class="btn btn-primary" href="{% url 'staff:create' %}">Tambah Baru</a>
{% endblock heading %}

{% block content %}
<table id="stafftable" class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>No</th>
            <th>Fullname</th>
            <th>Gender</th>
            <th>Mobile Phone Number</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    
    <tbody>
        {% for staff in object_list %}
        <tr class="clickable-row" data-href="{{ staff.get_absolute_url }}">
            <td>{{ forloop.counter }}</td>
            <td>{{ staff.nama }}</td>
            <td>{{ staff.gender }}</td>
            <td>{{ staff.nomor_hp }}</td>
            <td>{{ staff.status_sekarang }}</td>
            <td><a class="btn btn-success" href="{% url 'staff:update' staff.id %}">Update</a><a class="btn btn-danger" href="{% url 'staff:delete' staff.id %}">Hapus</a></td>
        </tr>
        {% empty %}
        <tr>
            <td></td>
            <td>Belum ada karyawan</td>
            <td></td>
            <td><a href="{% url 'staff:create' %}">Tambah Karyawan</a></td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}